### ISSUE TITLE
Would be nice to pass err.code to new error object

### ISSUE THREAD

**Issue by jhsware** [KTH/canvas-api#41]
https://github.com/KTH/canvas-api/blob/0f9b714191b24145ca55ccd67a69ca100af0b3be/src/utils.ts#L45

```
class CanvasApiError extends Error {
    constructor(gotError) {
        super(gotError.message);
        this.name = "CanvasApiError";
        this.code = gotError.code; //  <--- suggestion
        this.options = {
            headers: gotError.options.headers,
            url: gotError.options.url.toString(),
        };
        this.response = gotError.response;
        this.options.headers.authorization = "[HIDDEN]";
    }
}
```

Right now we don't get much discrimination between types of errors. Using the message feels brittle.

**Comment by exacs** [comment]
Sure!

We can include `code`. I will include it in https://github.com/KTH/canvas-api/pull/38

Just keep in mind that `code` is not the status code (500, 404, etc) but something like `ERR_NON_2XX_3XX_RESPONSE` (a code added by the library Got). If you want the status code, use `gotError.response.statusCode`

**Comment by jhsware** [comment]
Yesh I saw that. Perhaps one should move response.code to err.code given that the got err strings are dumbed down?

**Comment by exacs** [comment]
> Yesh I saw that. Perhaps one should move response.code to err.code given that the got err strings are dumbed down?

Not for now since it would be a breaking change.
