### ISSUE TITLE
Release 4.2.4 appears to be broken

### ISSUE THREAD

**Issue by jhsware** [KTH/canvas-api#52]
Missing /dist folder in [package published on Npmjs](https://www.npmjs.com/package/@kth/canvas-api?activeTab=versions).

**Comment by exacs** [comment]
Thanks for noticing it! 😄. Now it should be fixed:

- 4.2.4 deprecated: https://www.npmjs.com/package/@kth/canvas-api/v/4.2.4
- 4.2.5 published: https://www.npmjs.com/package/@kth/canvas-api?activeTab=versions
